obj-$(CONFIG_ACX_MAC80211) += acx-mac80211.o
acx-mac80211-obj-$(CONFIG_ACX_MAC80211_PCI) += pci.o
acx-mac80211-obj-$(CONFIG_ACX_MAC80211_USB) += usb.o
acx-mac80211-obj-$(CONFIG_ACX_MAC80211_MEM) += mem.o
acx-mac80211-objs := common.o $(acx-mac80211-obj-y)
obj-$(CONFIG_ACX_MAC80211_PCMCIA) += platform-pcmcia/
